version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  db:
    image: mysql:8.0.12
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/static/sql:/docker-entrypoint-initdb.d/:ro